### ISSUE TITLE
State of Riak TS?

### ISSUE THREAD

**Issue by l2dy** [basho/riak#1072]
The [docs](https://docs.riak.com/riak/ts/1.5.2/setup/installing/source/index.html#installing-from-github) ask me to clone this repository, but I can't find anything specific to Riak TS here. Has it been unified with Riak KV?

```sh
git clone --branch riak_ts-1.5.2 https://github.com/basho/riak.git
cd riak_ts-1.5.2
make locked-deps
make rel
```

**Comment by martinsumner** [comment]
There's been no work on Riak TS since basho folded.  A lot of very interesting work on Riak TS was done on it prior to basho folding, but with a lack of real-world users none of that work has been progressed. 

The tag referred to in the docs is present, you may still be able to build and run it - but given the lack of support for an up-to-date OTP release, I would not recommend using TS for any production use cases.

**Comment by l2dy** [comment]
Thanks for the information. I thought it was a branch and didn't check the tags.
