### ISSUE TITLE
`make install' target in the Makefile

### ISSUE THREAD

**Issue by seemantk** [basho/riak#203]
...is missing.  Instead of doing all those manual things in the rpm spec and deb control files, seems like it could all be centralized in the Makefile (make rel; make install) with overridable destination targets (e.g. make DESTDIR=/opt/basho/riak-test install).

Is there consideration for this?

**Comment by jaredmorrow** [comment]
I appreciate the comment, though I don't know if it is something we will add.  'make rel' makes a installation of riak on its own and the other commands in each package script moves those folders around where they should be on that distro.  Since each OS seems to do it slightly different I don't know how much work it will save to move that logic into the toplevel makefile.  In addition, as much as I can, I have tried to keep the packaging out of the top level makefile to keep it as small as possible (and it is already quite large).  Maybe I'm missing something obvious, which is very likely the case, so I hate to just shoot down your idea.  If a 'make install' target will make something easier for your use case, please let me know.  Also, gists / PR's for what you are intending are also very welcome, sometimes I can't quite see the light until someone shines it brightly into my eye!
