### ISSUE TITLE
/usr/sbin/riak script should not be trying to run

### ISSUE THREAD

**Issue by theslava** [basho/riak#289]
If /usr/sbin/riak is invoked as a user other than the riak user, it currently tries to restart itself using sudo and outputs the following message:
Attempting to restart script through sudo -H -u riak

It should not be trying to do that as it is possible that Riak is running on a system which does not have sudo installed. Unfortunately, sudo is not the only tool in existence that can do privilege escalation (for example: https://support.ca.com/cadocs/0/CA%20Access%20Control%2012%205%205-ENU/Bookshelf_Files/HTML/index.htm?toc.htm?1358999.html)
## 

Slava

**Comment by jaredmorrow** [comment]
In our packages, we require `sudo` as a dependency.  It might not be the perfect solution, but `sudo'`is what most people are familiar with so that is the choice we made.  If compiling from source, obviously you have the choice to change it to use whatever tool works best in your environment.

We support Solaris, FreeBSD, SmartOS in the BSD/Unix domain and all of them have sudo either by default or in packages.

**Comment by theslava** [comment]
If the /usr/sbin/riak script the only part of Riak that requires sudo simply because it tries to become the riak user, I do not agree that sudo should be a requirement for Riak.

## 

Slava

**Comment by jaredmorrow** [comment]
For now we will not be replacing sudo with sesudo as most users are willing to install sudo to control their ACL policy for Riak.  Thanks for reporting it, we will keep it in mind for releases down the road.
