### ISSUE TITLE
Improve Protobuf API

### ISSUE THREAD

**Issue by mchristiansen** [basho/riak#299]
The protobuf API lags significantly behind the HTTP API. At the very least it would be nice to have a stats call to get information about node health from a riak client.  Also, if the APIs matched it would allow for simpler implementations of any client APIs that try to provide both APIs as options.

**Comment by seancribbs** [comment]
I don't think we'll be adding stats to the PBC API because I understand we have a plan for having a separate "admin" interface that is single-protocol. Also, with how quickly the stats structure changes in each release, I doubt we could provide a message type that would make sense.

That said, we are making a strong effort to provide parity for all other features.
