### ISSUE TITLE
HyperLevelDB as a backend [JIRA: RIAK-1846]

### ISSUE THREAD

**Issue by mjp0** [basho/riak#337]
I'm not sure if this is the right repo for this but have you guys had the time to evaluate HyperLevelDB as a potential backend? At least according to the authors it's compatible with LevelDB so integration might not be very difficult. Their own benchmarks show a lot of performance improvements.

https://github.com/rescrv/HyperLevelDB
http://hyperdex.org/performance/leveldb/

**Comment by seancribbs** [comment]
We already have a fork of LevelDB as a backend, and it is heavily optimized for Riak's use-case. @matthewvon (our lead engineer on LevelDB) [has already said](https://news.ycombinator.com/item?id=5835098) that he will look into integrating HyperDex's changes when time permits.

**Comment by DeadZen** [comment]
I believe @matthewvon mentioned this was heavily optimized for Riak's _1.0_ use-case. We are well beyond that now (two years now with 3.0 on the roadmap), has there been anything more substantial than a cursory glance of the contrasts in the implementations? Maybe some Basho benchmarks?; I think the appropriate response here is quantitative because I fail to see how multiple writers per partition, not favoring reads over writes and easements on compaction are use cases that are not optimized for Riak... Understandably, multiple leveldb databases are used for partitions, but is that actually a comparably efficient strategy compared to the solutions provided here?; If so, then what is that evidenced by? Another aspect was write throttling, as I'm aware put fsms are throttled at an application level with sidejob so it seems the logic is already being re/placed outside of leveldb to provide selective back pressure to readers/writers (possibly even ironically linked to overload situations cited by some of the solutions implemented in @rescrv hyperleveldb repo and mentioned on http://hyperdex.org/performance/leveldb/). 
So I'm really curious, How's this story looking today?
