### ISSUE TITLE
Riak 2.0: investigate +A sizing problem for R16B01

### ISSUE THREAD

**Issue by slfritchie** [basho/riak#363]
As we're planning on using the R16B01 version of Erlang/OTP for the Riak 2.0 release, we need to investigate this problem:

http://erlang.org/pipermail/erlang-bugs/2013-August/003702.html
1. Confirm that it's real.
2. Develop process workaround, e.g. with Cuttlefish and with various Riak docs.  For example, what to do when upgrading Riak and keeping old vm.args (as default action)
3. Also apply to riak_ee packaging/Cuttlefish/docs/etc

**Comment by evanmcc** [comment]
As for 1. It does seem to be real, and something that will hit us on bitcask.

For example, a disk bound ramp up of bitcask (identical cluster and test load): 

R16B01, +A 64:

234.44444444444443 57.422222222222224
358.5944444444445 90.27222222222221 
363.52777777777777 89.95 
356.73333333333335 89.57777777777778
376.6166666666667 94.89444444444445 
369.9277777777778 92.26666666666667 
385.9222222222222 96.40555555555555 
373.38888888888886 92.82777777777778 
395.53333333333336 97.81666666666666 
393.05 97.12777777777778 

R16B01, +A 67 (workaround is prime-size worker pool):

549.0944444444444 135.24444444444444
717.7277777777778 177.95 
706.9888888888889 178.66666666666666
743.9555555555556 185.29444444444442
779.2388888888889 192.4111111111111 
779.6 193.7888888888889 
868.7 214.37222222222223 
911.75 227.2111111111111 
966.3888888888889 240.82777777777775
1124.3333333333333 282.69444444444446 

R15B01: 

606.3277777777778 150.9888888888889
979.7055555555556 243.48333333333332
985.3055555555555 244.20555555555558
1021.6277777777777 257.35 
1043.788888888889 261.55 
1085.7611111111112 272.67777777777775
1225.4111111111113 306.5777777777778 
1353.5388888888888 335.69444444444446 
1574.8666666666666 387.13888888888886 
1961.9833333333333 490.81666666666666 

First column is vnode_gets, second is vnode_puts.

Two takeaways from this: 
- R16B01 is much faster with a prime-sized async pool, which suggests that 1 is true.
- It's still slower than R15B01 even with the worker pool sized correctly.

If we end up shipping with this workaround rather than cherry-picking whatever patch the erlang team does for this, we need to note it prominently in the release notes.

**Comment by evanmcc** [comment]
It looks like R16B02 does fix this issue.  Leaving open for now as it isn't 100% clear to me if we can go with it for other reasons.

**Comment by jaredmorrow** [comment]
We are shipping R16B02, so closing this issue.
