### ISSUE TITLE
riak-debug + cuttlefish = can't find app.config

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#418]
On a Ubuntu 12 VM with 2.0.0pre4:

```
root@UBUNTU-12-YZTEST:~# riak-debug
.....................................Ecat: /etc/riak/app.config: No such file or directory
/usr/sbin/riak-debug: 407: [: =: argument expected
ls: cannot access /riak_core_ring*: No such file or directory
E.Ecat: /etc/riak/app.config: No such file or directory
/usr/sbin/riak-debug: 453: [: =: argument expected
.. /root/UBUNTU-12-YZTEST-riak-debug.tar.gz
```

**Comment by cmeiklejohn** [comment]
Yup; I'm tracking this along with the failed `riaknostic_rt` test.

**Comment by joedevivo** [comment]
@bsparrow435 should be involved here

**Comment by joedevivo** [comment]
riak-debug currently pulls from the app.config. That's where it gets interesting because of the conditional logic in cuttlefish that needs to be smart about which files exist. It goes like this:
- If there's no app.config and no vm.args in the etc dir, it generates them with cuttlefish from the riak.conf
- If there's only one of those in etc, it generates both, but uses the existing one from etc, and pulls in the other from cuttlefish
- If both exist, cuttlefish does nothing.

If riak has never been started or there's an error in the riak.conf, the app.config and vm.args will never be generated. For the first time, we're in a situation where we can't count on app.config existing. Fortunately for us, if this is the case, the only two pieces of information riak-debug pulls from the app.config will be empty anyway.

What's more confusing is that the only place that we can be sure the config is the one we're using is the generated app.config. I don't love the idea of replicating cuttlefish logic in riak-debug.

Now that I've written down where I think the problems are, let me float a solution that has popped into my head while writing this.

cuttlefish does it's thing through the cuttlefish_escript. That includes that conditional logic above. the cuttlefish escript is already included in the riak build. We could add a command line flag that queries the config, the way epath does for app.config. I actually like that alot, but probably can't get it done for tech preview. 

Until this issue is closed, riak-debug will work, it just won't include the riak logs or ring state.

**Comment by jaredmorrow** [comment]
See: https://github.com/basho/riak/issues/455  

Though this issue is older, I'm closing it since more tracking has been done in #455.
