### ISSUE TITLE
Make JavaScript MapReduce work reliably

### ISSUE THREAD

**Issue by roncemer** [basho/riak#427]
JavaScript is a ubiquitous language.  Nearly everyone knows it.  Erlang is an obscure language with strange constructs and syntax.  Almost no one uses it or cares to.

Any K/V store which is to be taken seriously in the market MUST have proper support for a popular language when it comes to their M/R implementation.

The hard-coded 5-second timeout on JavaScript script execution in erlang_js needs to go away, or at least be made configurable.

In every case where there is event the remotest possibility of a bad_utf8_character_code error occurring, that code needs to be fixed.  The interface between erlang and JavaScript needs to be made binary-safe and bullet-proof.

This idea of writing complex map and reduce functions in an obscure language like Erlang, then being forced to compile them and load them on every node in the cluster...that's for chumps.  We need to get the JavaScript M/R working properly, with first-rate support.

The documentation gives plenty of examples of JavaScript M/R implementations, but doesn't explain that JavaScript M/R really does blow chunks in Riak.

Let's light a fire under this, and get it fixed.

Also, why does Riak use the Spidermonkey JS engine when the V8 engine is newer and faster?  Or is that old news?  Has Spidermonkey really surpassed V8?

Riak has definite advantages over Mongo, Cassandra and HBase when it comes to reliability, scaling out with fewer servers, and low administration costs.

Now, let's make it better than all of these in terms of ease of use, especially in the area of JavaScript.

**Comment by roncemer** [comment]
I should add that I've been using Riak for a big-data project for several months now, and I like it.  But it could be much better if these issues were resolve instead of kicked down the road -- or making excuses as to why we don't want to solve them.  Let's just do this.

**Comment by beerriot** [comment]
Hi, @roncemer. I apologize for the delay in responding here. I attempted to write a more general response about JS improvement in Riak, but it got a bit unwieldy. So, instead I'm going to respond point by point for now, and possibly return with that broader-scope response later.

> JavaScript is a ubiquitous language. Nearly everyone knows it. Erlang is an obscure language with strange constructs and syntax. Almost no one uses it or cares to.

This is true only in the relative situation here. In the wider world, [C, Java, Objective-C, C++, C#, PHP, Basic, and Python are all more widely known](http://www.tiobe.com/index.php/content/paperinfo/tpci/index.html) and used than Javascript. Erlang, it's true, is even less popular, but "obscure" and "strange" are still quite relative. Any functional programmer will recognize lists and tuples. We agree, though, that it would be very nice for a user to not need to know Erlang to exploit Riak's distributive power to analyze the data it stores.

> Any K/V store which is to be taken seriously in the market MUST have proper support for a popular language when it comes to their M/R implementation.

I think there may be a false assumption embedded here. I don't think any KV store actually needs a MapReduce implementation to be taken seriously. I think KV stores mostly trade on their correctness, management, and performance (not necessarily in that order).

Furthermore, I think most users would actually prefer nearly any other wide-query system over MapReduce. As proof, look at all of the projects that try to hide Hadoop's MR behind languages that are very much not focused on those particular processing steps.

Ultimately, when a datastore does choose to expose a MapReduce interface, I think you're right that one of the concerns is what language it consumes. MapReduce is only simple to understand at a very high level; the nitty gritty about how data is processed efficiently, and what happens when bugs are encountered, is anything but trivial. A familiar language can make dealing with the rest of these hard problems less daunting, though care should be taken not to force complex concepts into an environment that is not friendly to them.

> The hard-coded 5-second timeout on JavaScript script execution in erlang_js needs to go away, or at least be made configurable.

Yes, it should be configurable. If you wanted to get involved with the project, I think this would make a great first issue to sink your teeth into. That timeout is there to keep Riak from starving for VMs when some too-long-running (possibly malicious) function is executed on all of them.

One tip: if your Javascript function is taking longer than five seconds to execute, there might be something else wrong. One typical problem is in JS reduce phases - the re-encoding/re-decoding produces more and more garbage, and takes longer and longer, as the function is run over and over when new inputs arrive. Fixing this can be as easy as [increasing the batch size, or even setting the phase to wait for all inputs before running at all](http://docs.basho.com/riak/1.2.0/references/appendices/MapReduce-Implementation/#Configuration-Tuning-for-Reduce-Phases).

Another tip: once you have made that timeout configurable, you'll likely also want to make the backoff/timeout in the VM pool's reservation code [`riak_kv_js_manager`](https://github.com/basho/riak_kv/blob/develop/src/riak_kv_js_manager.erl) configurable as well, or you'll end up with the same sort of hard-coded timeout problem when you're trying to run more MR queries than you have JS VMs.

> In every case where there is event the remotest possibility of a bad_utf8_character_code error occurring, that code needs to be fixed. The interface between erlang and JavaScript needs to be made binary-safe and bullet-proof.

I think there may be two parts to this issue. The first are bugs that we have missed. Riak does attempt to catch some native Erlang types that would cause encoding errors (see [`riak_kv_object_json`](https://github.com/basho/riak_kv/blob/develop/src/riak_object_json.erl)). Finding holes in that module would also be another great way to get involved with the project.

I fear that it may not be possible to solve the other part of the issue without significant restructuring. Data is passed between Riak and the JS VM as JSON data. Riak supports any binary blob as a key's value, but JSON has no "binary" type. So, it comes down to the choice between strings (which must be some valid Unicode encoding, so we're talking `\u` encoding, base64, or the like), and an array of integers (one per byte).

The restructuring would entail using something other than JSON for communication between Riak and the JS VM. We have occasionally discussed this option as a way to improve the performance as well, because JSON parsing is often a significant amount of the execution time. Something like [BERT](http://bert-rpc.org/) or [Protocol Buffers](https://developers.google.com/protocol-buffers/) might be interesting.

> This idea of writing complex map and reduce functions in an obscure language like Erlang, then being forced to compile them and load them on every node in the cluster...that's for chumps. We need to get the JavaScript M/R working properly, with first-rate support.

For anyone doing serious MR, the same problem exists for Javascript. The best way to use it is to write the code in a file and deploy that file on the cluster. Then, it's possible to just name the functions in phase definitions instead of sending the entire source with every request. This is not only more efficient from the client to the Riak node, but also between the Riak node and the Javascript VM.

Developing a system to install code across the cluster would be a fun project for anyone who wanted to learn more about `riak_core`, and the new cluster metadata facilities coming in Riak 2.0. Spreading information via the plumtree/gossip protocols embedded there could improve many aspects of deploying either Javascript or Erlang code for MapReduce.

> The documentation gives plenty of examples of JavaScript M/R implementations, but doesn't explain that JavaScript M/R really does blow chunks in Riak.
> 
> Let's light a fire under this, and get it fixed.

Improvements depend on individuals making them happen. Javascript MapReduce is currently not the primary focus of any Basho developer's time. We do continuously discuss its outstanding issues and possible futures, but as yet, we have found other improvements more pressing and more promising. If you are passionate about improving JS MR, though, please submit bug reports and pull requests, and try to find other people in the community to help you. We commiters are much more responsive to small bits of obvious work than we are to vague calls for improvement.

> Also, why does Riak use the Spidermonkey JS engine when the V8 engine is newer and faster? Or is that old news? Has Spidermonkey really surpassed V8?

Briefly: history.

History 1: legacy support. For a long time we needed to be able to deploy Riak on Solaris running on SPARC. We also insisted that Riak support the exact same feature set on all platforms. The version of Spidermonkey we use was the only one that could give us this at that time.

History 2: old V8 architecture. When V8 was first available, its garbage collection design was not compatible with the way Riak wanted to use VMs. I believe this is no longer the case.

Unfortunately, we were trapped on our version of Spidermonkey for so long that we finally just stopped looking. A few people have since offered to update the version that we use, at least, but as yet none has come through. Again, it comes down to individuals being the only force for improvement, and this improvement hasn't climbed to the top of anyone's focus yet.

The only warning I'll add is that Javascript is made available in Riak in more contexts than MapReduce (e.g. commit hooks). Watch out for those gotchas if interfaces need to change.

> But it could be much better if these issues were resolve instead of kicked down the road

It is hard to define "solved" in a changing, scaling system. What is solved for today's use case is not necessarily solved for tomorrow's. Believe it or not, even this Javascript MapReduce system was good enough for some problems at one time. It needs improvement for the future, but iterative improvement is the name of the game, or we'll all be out of jobs shortly.

---

So, that's the brief version. There's a ripe field of issues to tackle. Hopefully I've given enough leads for you and others reading along to being to tear in. Thanks for the feedback.
