### ISSUE TITLE
2.0 in mac homebrew lib warnings

### ISSUE THREAD

**Issue by asparagui** [basho/riak#429]
Hello, I attempted to add the new pr5 version to the mac homebrew package manager.  The 2.0.0-pre5 version is triggering an audit warning on the jenkins script used there:

Error Message

failed: brew audit --devel riak
Stacktrace

```
    Error: 1 problems in 1 formulae
```

riak:
- Non-libraries were installed to "/usr/local/Cellar/riak/2.0.0-pre5/lib".
  Installing non-libraries to "lib" is discouraged.
  The offending files are:
  /usr/local/Cellar/riak/2.0.0-pre5/lib/00-riak.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/01-riak_core.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/02-riak_api.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/03-riak_kv.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/04-riak_sysmon.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/05-bitcask.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/06-riak_control.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/10-multi_backend.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/11-leveldb.schema
  /usr/local/Cellar/riak/2.0.0-pre5/lib/20-yokozuna.schema

Would it be possible to move these *.schema files to a subdirectory?

**Comment by adamv** [comment]
Alternatively, what is the recommended way of installing riak in a "non-conflicting" way on a system?

**Comment by jaredmorrow** [comment]
So, I haven't looked at homebrew and how it does things, but we have a notion of platform_\* directories that get used both for installation and for modules to know where to look for things.  The .schema files do act as library files to us because they are typically not changed once installed and they are used as a template to generate the new configuration files.  The generated configuration files, since they are generated, go into the platform_data_dir for each platform, which makes sense.  The *.schema files go into the platform_lib_dir on each platform.  I personally feel this is a good place, because they don't feel like a /etc/riak/ type thing that is expected to be edited, but I'd also like to help you get this working.  For the moment I'm going to /cc @joedevivo so he can think about making a subdirectory in the platform_lib_dir and I can think about how that might affect packaging on various platforms.

**Comment by asparagui** [comment]
We reworked how we're packaging risk slightly, so no need to touch anything on your end.  Sorry about the bother and good luck w/ the 2.0 release.
