### ISSUE TITLE
Riak security "add-source all" adds two source records.

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#470]
This doesn't seem to have any negative effects other than the `print-sources` output:

```
# riak-admin security print-sources
+--------------------+----------+----------+----------+
|       users        |   cidr   |  source  | options  |
+--------------------+----------+----------+----------+

# riak-admin security print-users
+----------+---------------+----------------------------------------+------------------------------+
| username |     roles     |                password                |           options            |
+----------+---------------+----------------------------------------+------------------------------+

# riak-admin security add-source all 127.0.0.1/32 trust

# riak-admin security print-sources
+--------------------+------------+----------+----------+
|       users        |    cidr    |  source  | options  |
+--------------------+------------+----------+----------+
|                    |127.0.0.1/32|  trust   |    []    |
|        all         |127.0.0.1/32|  trust   |    []    |
+--------------------+------------+----------+----------+
```

**Comment by jaredmorrow** [comment]
There has been work from @macintux on the CLI UX for security b/w pre18 and pre20, any idea if these issues still exist?

**Comment by jaredmorrow** [comment]
Sorry, accidental "close & comment" button push.

**Comment by lordnull** [comment]
Issue exists, but is a display issue, not a code error. For each user in a source, one source row is added; even is the user added is 'all'. The user lists is combined for display. Then, if a source has 'all' in the user list, an additional row is added to the display. Because the source in the example has no users explicitly added, the row before the 'all' row has an empty list of users.

Possible solutions: 
- If there are no explicit users, don't show the explicit user row.
- Add documentation that a row with no users means that if the 'all' entry for the source is removed, no all users from that source will be effected.

Note that in both cases, if the documentation doesn't already cover this case, it should:

<pre>+--------------------+------------+----------+----------+
|       users        |    cidr    |  source  | options  |
+--------------------+------------+----------+----------+
| jackson, c, b, a,  |127.0.0.1/32|  trust   |    []    |
|       jones        |            |          |          |
|        all         |127.0.0.1/32|  trust   |    []    |
+--------------------+------------+----------+----------+</pre>

If the 'all' source is removed, users jackson, c, b, a, and jones will still be trusted.

**Comment by macintux** [comment]
Touching this; I've had it on my list for a very long time to fix this, so hope to take a look soon.

**Comment by macintux** [comment]
Trivial patch forthcoming

**Comment by macintux** [comment]
PR submitted, also submitted docs issue basho/basho_docs#1111

**Comment by macintux** [comment]
Closing, PR is being merged
