### ISSUE TITLE
2.0 pre18 some questions

### ISSUE THREAD

**Issue by eminarcissus** [basho/riak#510]
When working with localhost:8098/stats, I get the version of riak_kv_version of 1.4.2-529-g2ea327b, which I can get correct version info from pbc with
[RiakPBC,client] 2.0.0pre18.

Also for yokozuna pbc interface, it only supports q, which didn't support fq,facet or any solr query arguments, so will it ever going to support that? or prefer to use a solr client instead?

**Comment by rzezeski** [comment]
> Also for yokozuna pbc interface, it only supports q, which didn't support fq,facet or any solr query arguments, so will it ever going to support that? or prefer to use a solr client instead?

The PBC interface is limited to the operations supported by legacy
Riak Search. If you need to use features like faceting then you'll
have to use HTTP for now. The `fq` param is supported but it is called
`filter` in the current PBC interface.

**Comment by rzezeski** [comment]
> When working with localhost:8098/stats, I get the version of riak_kv_version of 1.4.2-529-g2ea327b, which I can get correct version info from pbc with
> [RiakPBC,client] 2.0.0pre18.

The `riak_kv_version` is based on the `riak.app` file which has its
version generated based on the last tag (`git describe --always --tags`).
In the case of 2.0.0pre18 the last tag on riak_kv was 1.4.2
and there have been 529 commits since. We haven't yet tagged the
riak_kv repo with 2.x because we are still in pre-release stage.

The version coming back from PBC is the overall Riak version which is
currently different from the riak_kv version.
