### ISSUE TITLE
allow_mult=true on new bucket and siblings

### ISSUE THREAD

**Issue by oleksiyk** [basho/riak#511]
Is there any delay before `allow_mult=true` option for a new bucket is gossiped between riak 2.0 cluster nodes? Because if I try to concurrently put several values without vclocks to the same key (and same new bucket) - I don't get any siblings, just a single value. But if I first set new bucket properties (even empty, so all defaults), then wait ~500ms and then concurrently put several values - I get that amount of siblings, which is what I expect when allow_mult=true. It looks like `allow_mult=true` is first gossiped between cluster nodes before it really becomes active for a new bucket?

And later the following type of message appears in logs:

```
2014-03-15 23:07:56.540 [info] <0.17437.6>@riak_kv_exchange_fsm:key_exchange:252 Repaired 1 keys during active anti-entropy exchange of {1141798154164767904846628775559596109106197299200,3} between {1141798154164767904846628775559596109106197299200,'dev1@127.0.0.1'} and {1164634117248063262943561351070788031288321245184,'dev2@127.0.0.1'}
```

Running local 'devrel' cluster, commit f0d02eb9

**Comment by jrwest** [comment]
are you working with bucket types as well? we recently reverted the default for `allow_mult` to `false` for buckets under the default type [1]. Defaults are stored locally on each node and are not gossiped so there should be no delay when using them. If you are setting custom properties (defaults or otherwise) there may be some delay (usually microseconds in a devrel) as the update propagates around the cluster.

[1] https://github.com/basho/riak_kv/pull/825

**Comment by oleksiyk** [comment]
My order of operations is (its a test actually):
1. set bucket properties (via `RpbSetBucketReq`): allow_mult=true
2. insert several values without vclocks

I don't use bucket types. 
If there is no delay between 1. and 2. then I don't get siblings, if I wait a bit between 1. and 2. then I get siblings as expected.

So if allow_mult=false is default again as it was in 1.4 then it all makes sense. Would it be default in all future 2.x?

**Comment by jrwest** [comment]
For the `default` bucket type (which you are working with) `allow_mult=false` will continue to be the default. This is in order to minimize potential surprises on upgrade (data you expected to never have siblings all of a sudden does). However, we believe `allow_mult=true` is the correct default, so bucket types, by default, use `allow_mult=true`. So yes, the scenario you describe is possible.

**Comment by oleksiyk** [comment]
Thanks!
