### ISSUE TITLE
Tweak logging defaults

### ISSUE THREAD

**Issue by evanmcc** [basho/riak#517]
Two changes, both in the interest of better default visibility:
1. Increase the log rolling to weekly rather than daily.
2. Change the log rate throttle from 100 -> something large.  I'd suggest 500 or a thousand, but people might want to discuss.  I suggest them because I think that we should err on the side of visible-but-slow.

**Comment by rzezeski** [comment]
+1 to > 100. I see log msgs getting dropped during riak startup.

**Comment by Vagabond** [comment]
We should instead raise the limit after startup if we care about all the startup noise. The limit is there for a _very_ good reason:

http://hijacked.us/~andrew/lager.png

http://hijacked.us/~andrew/error_logger.png

If the limit is too high, the node gets overwhelmed before the dropping can kick in.

**Comment by Vagabond** [comment]
Err, lower the limit, I mean.

**Comment by evanmcc** [comment]
Is it possible to quantify what's safe?  the 100/s limit has made some log
sets I've looked at entirely useless because there are periods where
thousands of messages were dropped.  How hard would to be to add
syslog-like repeat message folding?  I understand why the limit is there,
I'm just arguing that it's far too strict by default.

**Comment by Vagabond** [comment]
The problem is that errror_logger is _seriously_ flawed in its implementation. It provides 0 backpressure so that its mailbox can get loaded up with millions of messages.

Originally we had some code to drop duplicate messages, but it turned out to be slow enough that it didn't really help when an error_logger storm kicked in. The tradeoff is lose some error_logger messages or crash the node. In what cases are you seeing that many error logger messages?

**Comment by Vagabond** [comment]
'Safe' is going to be very system dependant, unfortunately. I tried to pick a reasonable limit that should be safe on all but the slowest machines.

**Comment by evanmcc** [comment]
At a customer with a very large cluster of very heavily populated bitcask
partitions, upgrading from 1.3 -> 1.4.  The nodes got sad and kv wouldn't
start, but we couldn't figure out what was going on.

```
2014-03-20 16:53:22.442 [warning] <0.6.0> lager_error_logger_h dropped 46
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:53:23.015 [warning] <0.6.0> lager_error_logger_h dropped 216
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:57:34.000 [warning] <0.6.0> lager_error_logger_h dropped 1271
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:57:35.000 [warning] <0.6.0> lager_error_logger_h dropped 2412
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:57:36.000 [warning] <0.6.0> lager_error_logger_h dropped 11
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:58:38.000 [warning] <0.6.0> lager_error_logger_h dropped 5
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:58:39.000 [warning] <0.6.0> lager_error_logger_h dropped 18
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:58:44.610 [warning] <0.6.0> lager_error_logger_h dropped 5
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:58:47.230 [warning] <0.6.0> lager_error_logger_h dropped 5
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 16:58:48.000 [warning] <0.6.0> lager_error_logger_h dropped 3
messages in the last second that exceeded the limit of 100 messages/sec
2014-03-20 18:00:20.131 [warning] <0.6.0> lager_error_logger_h dropped 8
messages in the last second that exceeded the limit of 100 messages/sec
```

**Comment by jonmeredith** [comment]
I regularly see dropped messages on startup on my year old mbp.  Normal startup shouldn't trip the threshold.

Is it feasible to have lager have a higher message/sec threshold during the initial application startup, then perhaps dropped back once all applications started?

The other way to attack it is to look and see if any of the startup messages should be lowered in priority.

**Comment by Vagabond** [comment]
Remember, this _only_ affects messages coming from error_logger. Bitcask uses error_logger because we didn't want to tie it to lager with a dependancy.

We don't use phased startup, so when is riak 'up'? There's API for changing the error_logger high water mark:

https://github.com/basho/lager/blob/master/src/error_logger_lager_h.erl#L73

Now, what evan saw where it only reports the dropped message, is weird. I've never seen it do that. It should only drop the log messages that exceed the threshhold for that second, which usually gives you a decent sampling what is storming the error logger without actually killing it. This might be a bug, so I'd be interested if it was possible to reproduce.

A year ago I did a lot of testing to find a reasonable default for this, I won't stop you guys changing the defaults, but when error_logger starts OOMing nodes again (and the logs get lost anyway), don't be surprised.

**Comment by evanmcc** [comment]
would it be reasonable to move bitcask/eleveldb to a macro-based or
environment toggled log selector?  so in riak, we use lager, whatever else,
we use error_logger?

**Comment by evanmcc** [comment]
As a note, lager is already a dependency of bitcask now that cuttlefish is
included.  Maybe we should just move it over?

**Comment by macintux** [comment]
@evanmcc What are next steps here?

**Comment by evanmcc** [comment]
Yet another inconclusive discussion.  I am just going to close it and move the potential work over to bitcask.
