### ISSUE TITLE
Riak search index being corrupted sometimes. [JIRA: RIAK-2110]

### ISSUE THREAD

**Issue by mogadanez** [basho/riak#547]
I'm indexing  data with Solr interface
http://docs.basho.com/riak/latest/dev/references/search-indexing/#Indexing-using-the-Solr-Interface

Sometimes it is becomes to wrongs state(  i believe under some load, simultaneous write ) - numFound returns more  count than data, for example:
http://db.proofme.com:8098/solr/test-index/select?q=field1:value1 returns

```
<response>
<lst name="responseHeader">
<int name="status">0</int>
<int name="QTime">3</int>
<lst name="params">
<str name="indent">on</str>
<str name="start">0</str>
<str name="q">owner:field1:value1</str>
<str name="q.op">or</str>
<str name="filter"/>
<str name="df">value</str>
<str name="wt">standard</str>
<str name="version">1.1</str>
<str name="rows">2</str>
</lst>
</lst>
<result name="response" numFound="2" start="0" maxScore="0.353553">
<doc>
<str name="id">8599253141758</str>
<str name="name">Koala</str>
<str name="field1">value1</str>
</doc>
</result>
</response>
```

It have  numFound="2"  but only one document.
If I add parameter fl=id, It returns 2 identical ids for me.

```
<response>
...
<result name="response" numFound="2" start="0" maxScore="0.0">
<doc>
<str name="id">8599253141758</str>
</doc>
<doc>
<str name="id">8599253141758</str>
</doc>
</result>
</response>
```

Then, when I delete index with Solr interface
http://docs.basho.com/riak/latest/dev/references/search-indexing/#Deleting-using-the-Solr-Interface

it is delete only One of them, second one is stayed as phantom, and I cannot remove it at all.

Does it any way to cleanup it?
How to prevent this situation in future?
I've noticed that internal _rsid_... bucket props does not have allow_mult or last_write_wins, so probably it is concurrency issue.

**Comment by mogadanez** [comment]
Looks like actually remove index leave item in that state

Sequence ( probably have more steps that need for reproduce ), operations not overlap, doing one by one.

23:38:59.925 - Add index

```
<add>
  <doc>
    <field name="id">8599212460240-e85d22fd888746f9862a0dde04d66f4f</field>
    <field name="originalID">e85d22fd888746f9862a0dde04d66f4f</field>
    ...
  </doc>
</add>
```

23:38:59.942 - Got response

23:39:00.866 - Add index ( same data inserted over ) 

```
<add>
  <doc>
    <field name="id">8599212460240-e85d22fd888746f9862a0dde04d66f4f</field>
    <field name="originalID">e85d22fd888746f9862a0dde04d66f4f</field>
    ...
  </doc>
</add>
```

23:39:00.866 - Got response

23:39:01.514 - Remove index

```
<delete>
  <id>8599212460240-e85d22fd888746f9862a0dde04d66f4f</id>
 </delete>
```

23:39:01.529 - Got response

23:39:01.547 - Add index 

```
<add>
  <doc>
    <field name="id">8599212458595-e85d22fd888746f9862a0dde04d66f4f</field>
    <field name="originalID">e85d22fd888746f9862a0dde04d66f4f</field>
    ...
  </doc>
</add>
```

23:39:01.547- Got response

After that:
q=originalID:e85d22fd888746f9862a0dde04d66f4f&fl=id returns:

```
<result name="response" numFound="2" start="0" maxScore="0.0">
<doc>
<str name="id">8599212458595-e85d22fd888746f9862a0dde04d66f4f</str>
</doc>
<doc>
<str name="id">8599212460240-e85d22fd888746f9862a0dde04d66f4f</str>
</doc>
</result>
```

q=originalID:e85d22fd888746f9862a0dde04d66f4f returns:

```
<result name="response" numFound="2" start="0" maxScore="0.353553">
<doc>
<str name="id">8599212458595-e85d22fd888746f9862a0dde04d66f4f</str>
<str name="originalID">e85d22fd888746f9862a0dde04d66f4f</str>
</doc>
</result>
```

I cannot reproduce with same sequence( update index over existing ) via curl running it one by one, so i believe main reason is in concurrency

riak 1.4.8, cluster of 5 nodes, aws

**Comment by mogadanez** [comment]
Reproduced also without index over with same Id( delete every time )
http://joxi.ru/Q25-UxjKTJAlTvTn20A

q=originalID:2196661f49c640378952200f8150734e&fl=id

```
<result name="response" numFound="2" start="0" maxScore="0.0">
<doc>
<str name="id">8599205980559-2196661f49c640378952200f8150734e</str>
</doc>
<doc>
<str name="id">8599205982553-2196661f49c640378952200f8150734e</str>
</doc>
</result>
```

q=originalID:2196661f49c640378952200f8150734e

```
<result name="response" numFound="2" start="0" maxScore="0.353553">
<doc>
<str name="id">8599205980559-2196661f49c640378952200f8150734e</str>
<str name="originalID">2196661f49c640378952200f8150734e</str>
</doc>
</result>
```

**Comment by mogadanez** [comment]
Since  Riak 2.0 will stop Solr update interfaces ( https://github.com/basho/riak_search/issues/141#issuecomment-35469036 )

I remake it for now to new paradigm

```
Write it like Riak. Query it like Solr.
```

**Comment by mogadanez** [comment]
Reopened, because it is not helps.

Now I use another bucket to store re-structured data.
bucket options:

```
{
props: {
allow_mult: true,
basic_quorum: false,
big_vclock: 50,
chash_keyfun: {
mod: "riak_core_util",
fun: "chash_std_keyfun"
},
dw: "quorum",
last_write_wins: false,
linkfun: {
mod: "riak_kv_wm_link_walker",
fun: "mapreduce_linkfun"
},
n_val: 3,
name: "ordered-proofs-v3",
notfound_ok: true,
old_vclock: 86400,
postcommit: [ ],
pr: 0,
precommit: [
{
mod: "riak_search_kv_hook",
fun: "precommit"
}
],
pw: 0,
r: "quorum",
rw: "quorum",
search: true,
small_vclock: 50,
w: "quorum",
young_vclock: 20
}
}
```

So, instead post to solr index interface I  save and remove items from this bucket, and riak_search_kv_hook should handle it and maintain  search index. 
But  problem still here. With riak search i get count  more data that exists in bucket

**Comment by rzezeski** [comment]
Are you trying to use the new search in Riak 2.0 now?  If so the `riak_search_kv_hook` has nothing to do with new search.

**Comment by mogadanez** [comment]
No, I'm still in 1.4.8 in production. Does 2.0 is ready to use in
production?

пятница, 23 мая 2014 г. пользователь Ryan Zezeski написал:

**Comment by rzezeski** [comment]
> No, I'm still in 1.4.8 in production. Does 2.0 is ready to use in
> production?

2.0 is still under development.  There is a beta version available and we are pushing hard to get final out but is probably another month or so away.  But all efforts have been focused on the new search for some time now as it is replacing legacy search in 2.0.

That said, you shouldn't be having the issues you are.  Can you share the exact steps you did for the bucket-based indexing (you should definitely avoid the solr update interface in legacy search) so that I can try running on my side.  That is, if you could show me the exact shell commands and code you are using that would be very helpful.

**Comment by mogadanez** [comment]
Reproduce:
https://github.com/mogadanez/riak-search-index-test

It fails not every time, sometimes at first attempt, sometimes from 20th.
It fails only on cluster setup( 5 nodes with haproxy in front, AWS, c3.large, Debian, Riak 1.4.8 )

UPDATE:
~~Cannot reproduce on  5 nodes c3.xlarge cluster with **EBS optimized** , so i belive some micro-racing conditions appears.~~
UPDATE2:
It still reproduced with EBS optimized, but need more attempts,
- I also try:  use last_write_wins:true - **still reproduce**.
- Add delay ( 1sec ) between Save and remove -   **still reproduce**.

**Comment by rzezeski** [comment]
I haven't run the code but noticed you are using allow_mult:

https://github.com/mogadanez/riak-search-index-test/blob/master/app.js#L82

Riak Search in 1.4.8 does not support siblings.  The new search in 2.0 does.  If you keep `allow_mult` set to false then it should work but you will then rely on wall clock time for resolution.  I noticed you set `last_write_wins: true` but that doesn't do what you probably think it does; it is poorly named.  That setting means that a write will clobber its previous version.  The "last write wins" behavior you want is setting `allow_mult: false`.

**Comment by mogadanez** [comment]
I able to reproduce it  with allow_mult: false and last_write_wins: false
Also, simplest reproduce sequence is Save, Remove, without any siblings or concurrent writes.

I add test with allow_mult: false ( in separate new bucket, so it never have  allow_mult: true  )

**Comment by mogadanez** [comment]
I remove 2 nodes from cluster,  and it now harder to reproduce. sometimes 20000 retries will not reproduce issue.

And it completely stop reproduced when I back to single node setup( runs tests several hours )

**Comment by rzezeski** [comment]
@mogadanez I'm going to try running your test program today but did you check the logs on all your machines?  Deleting requires reading a special object that contains the postings list and then sending an update to each node to delete its relevant postings and finally deleting the special postings list object.  Perhaps the second step is failing to send the deletes but the third step is still proceeding; causing postings to exist for objects that have since been deleted.  If this is the case perhaps there are entries in the log about failed updates.

**Comment by rzezeski** [comment]
@mogadanez I was not able to reproduce with your program.  However,
looking more closely at your comments I noticed the issue you see is
that `numFound` does not equal the length of the `docs` section
**UNLESS** you set `fl=id`.  This immediately made the issue obvious
to me, let me explain.

Riak Search (pre 2.0) uses a separate backend for the inverted index
(called merge_index).  This is where the postings for an object are
stored and the data structure which is used to answer queries.
However, RS also stores a special object of its own in the KV backend
that contains 1) the verbatim value for each field and 2) the postings
for the field after analysis.  That is, 3 things are written when you
index a KV object:
1. the KV object itself,
2. the special RS object with field values and postings,
3. the postings in merge_index (MI)

A query with no field list (`fl`) specified will first query MI to get
the identifier for each matching object; then it will use each ID to
fetch the special object to return the stored fields in the results.
However, there is an optimization.  If `fl=id` then only the ID needs
to be returned and thus the second step, retrieving the special
objects, can be avoided entirely.  In one case the special objects are
retrieved in the other they aren't.  This is the reason behind the
`numFound != docs.length` issue.  The `numFound` comes from the number
of results by MI, but the docs list will depend on the `fl`.  When
these numbers do not match it indicates that the postings exist in
merge index but the special object does not.  This brings us to
delete.

The reason the special object has a copy of the postings is so that RS
knows what to delete from MI when an object is deleted.  When an
object is deleted it fetches the special object, extracts the
postings, and sends requests to delete them from the various MI
servers (note that this is internode communication, not just local)
[1].  If those request fail but the the special object is still
deleted then the inconsistency you witnessed will occur.  After
looking at the code I've determined that these requests are not
checked for success and the special object is deleted unconditionally.
**This is a bug in RS**.

As I said, I was not able to reproduce on a 5-node stagedevrel
cluster.  My guess is your AWS/EBS deployment is making it easier for
some of these requests to fail.  In any case, this is a nasty bug.
The only way to fix inconsistency like this in Riak Search is to
re-index all your data for that bucket.  This is one of the many
reasons I recommend new users of Riak to avoid the existing Riak
Search.  The new version in 2.0 does not have these issues.  I realize
that 2.0 is not an option for you since it is not final yet (I don't
blame you, smart thinking) but I also would not recommend using the
Riak Search in
1.4.8.

[1]: You can see the gory details here: https://github.com/basho/riak_search/blob/develop/src/riak_search_kv_hook.erl#L185

**Comment by jwmtllc** [comment]
I understand this is closed but I ran into something similar. I had a Solr index that I was unable to delete. My error was that I had accidently associated two buckets with the same bucket-type, the bucket-type associated with my index. This may be okay in some cases. In my case the identical lookup key was created twice (along with additional data I did not want indexed!). I was able to find this error by looking at the yz_rb field from a curl invocation on the index. The remedy was to run a curl -XDELETE on both buckets (with the same key). I believe I have the latest version of Riak KV.
