### ISSUE TITLE
Riak buildable from source on Erlang R17 ?

### ISSUE THREAD

**Issue by ks** [basho/riak#648]
Currently this requires a lot of (trivial) changes on many places. 

Any plans to make the building work out of the box?

**Comment by cmeiklejohn** [comment]
Historically, we've only ever advanced the version of the supported runtime at major revisions of Riak, because it requires a large amount of testing to ensure that there are no unforeseen performance penalties.  That said, Riak 2.0 (released September 2, 2014) was the first release to ship with R16 and there are no current plans for moving to 17 in the short term.  We will reevaluate when identifying features targeted for the next major release.
