### ISSUE TITLE
Poor documentation for implementing a secure client [JIRA: RIAK-1618]

### ISSUE THREAD

**Issue by AndreasMadsen** [basho/riak#684]
There is no documentation for `RpbStartTls` and almost non for `RpbAuthReq`, it would be nice with a small section about how to implement a secure client connection.

**Comment by jaconstantine** [comment]
+1

**Comment by pyrrho** [comment]
Thanks for raising these concerns, guys!
As this issue is specifically calling out documentation, it can't really be solved in the base Riak repository. I've gone ahead and opened up an [identical issue](https://github.com/basho/basho_docs/issues/1575) in our [Basho Docs](https://github.com/basho/basho_docs) repository, and we should be able to get these improvements made there. As such, I'm going to close out this issue.

Thanks again!
