### ISSUE TITLE
Primary key condition parsing [JIRA: RIAK-2299]

### ISSUE THREAD

**Issue by erikleitch** [basho/riak#793]
When SQL queries are parsed, WHERE clauses involving primary keys are consumed and converted to start/end key pairs (and not passed to the backend filtering).

This works for things like: **WHERE time > 100 AND time < 400**, but is insufficient for handling combinations of operators like **WHERE time > 100 AND time != 400**.  These sorts of conditions cannot be converted into simple ranges.

To fix this, the parser should only consume WHERE clauses involving range operators (<, <=, >, >=) but pass other operators as part of the backend filter.  (When I talked to Gordon about this the other day, he stated that this was the original intention, but I have explicitly checked this and the code does not currently pass _any_ conditions on primary keys to the backend)

NB: conversion of primary key conditions to a simple start/end key pair will also fail for OR clauses (ie, **WHERE time < 200 OR time > 400**).  Under our current model these would have to be converted into two separate range scan queries to the backend.  I have not yet checked that this is handled correctly (but I will!)

**Comment by Basho-JIRA** [comment]
Re-assigning this to Andy, since it's really a change in the erlang parser code that needs to happen, and I suspect he's a lot more familiar with it than I am.  Happy to work on it too, but I'll wait for Andy to have a first crack at it. 

**_[posted via JIRA by Erik Leitch]**_

**Comment by Basho-JIRA** [comment]
Working on this currently. 

**_[posted via JIRA by Andy Till]**_

**Comment by Basho-JIRA** [comment]
And as you noted, this is:

# partly the unbounded range query problem

ie, we don't support time > 100, therefore can't support time > 100 AND time != 400
which we've decided is _definitely not_ part of TS1.0, in which case we just need to document what's allowed and not allowed for TS1.0

# partly error handling

we should throw an error then if we get passed a query like time > 100 AND time != 400
which _should definitely_ be part of TS1.0, and 

# partly fixable

time > 100 AND time < 400 AND time != 300 could be supported since it's bounded, but we have to pass the last clause to the filter
which _could_ be part of TS1.0

This last bit is tricky, though.  What if someone passes time > 100 AND time < 1000 AND time < 300 AND time > 200?  You'd have to sort through all the time clauses to figure out 1) if you _can_ construct a bounded query, and if so 2) what's the most liberal bound you can construct (ie, time > 100 AND time < 1000 in the above example), and then pass all the rest as part of the filter.  I don't know how much work that is in practice, so do we pursue this now or leave it for a later TS release?

Maybe the best path for now is not to allow these sorts of queries, and make sure we throw meaningful errors if we get an unbounded query?  

[~atill] you should comment on this when you've had a chance to scope out the work (or you may already know the answer). 

**_[posted via JIRA by Erik Leitch]**_

**Comment by Basho-JIRA** [comment]
And as you noted, this is:

# partly the unbounded range query problem

ie, we don't support time > 100, therefore can't support time > 100 AND time != 400
which we've decided is _definitely not_ part of TS1.0, in which case we just need to document what's allowed and not allowed for TS1.0

# partly error handling

we should throw an error then if we get passed a query like time > 100 AND time != 400
which _should definitely_ be part of TS1.0, and 

# partly fixable

time > 100 AND time < 400 AND time != 300 could be supported since it's bounded, but we have to pass the last clause to the filter
which _could_ be part of TS1.0

This last bit is tricky, though.  What if someone passes time > 100 AND time < 1000 AND time < 300 AND time > 200?  You'd have to sort through all the time clauses to figure out 1) if you _can_ construct a bounded query, and if so 2) what's the most liberal bound you can construct (ie, time > 100 AND time < 1000 in the above example), and then pass all the rest as part of the filter.  I don't know how much work that is in practice, so do we pursue this now or leave it for a later TS release?

Maybe the best path for now is not to allow these sorts of queries, and just make sure we throw meaningful errors if we get an unbounded query?  

[~atill] you should comment on this when you've had a chance to scope out the work (or you may already know the answer). 

**_[posted via JIRA by Erik Leitch]**_

**Comment by Basho-JIRA** [comment]
And as you noted, this is:

# partly the unbounded range query problem

ie, we don't support _time > 100_, therefore can't support _time > 100 AND time != 400_
which we've decided is _definitely not_ part of TS1.0, in which case we just need to document what's allowed and not allowed for TS1.0

# partly error handling

we should throw an error then if we get passed a query like _time > 100 AND time != 400_
which _should definitely_ be part of TS1.0, and 

# partly fixable

_time > 100 AND time < 400 AND time != 300_ could be supported since it's bounded, but we have to pass the last clause to the filter
which _could_ be part of TS1.0

This last bit is tricky, though.  What if someone passes _time > 100 AND time < 1000 AND time < 300 AND time > 200_?  You'd have to sort through all the time clauses to figure out 1) if you _can_ construct a bounded query, and if so 2) what's the most liberal bound you can construct (ie, _time > 100 AND time < 1000_ in the above example), and then pass all the rest as part of the filter.  I don't know how much work that is in practice, so do we pursue this now or leave it for a later TS release?

Maybe the best path for now is not to allow these sorts of queries, and just make sure we throw meaningful errors if we get an unbounded query?  

[~atill] you should comment on this when you've had a chance to scope out the work (or you may already know the answer). 

**_[posted via JIRA by Erik Leitch]**_

**Comment by Basho-JIRA** [comment]
PR https://github.com/basho/riak_kv/pull/1271 

**_[posted via JIRA by Andy Till]**_
