### ISSUE TITLE
Riak TS is versioned incorrectly [JIRA: RIAK-2550]

### ISSUE THREAD

**Issue by lukebakken** [basho/riak#835]
This should be `2.1.1`:

https://github.com/basho/riak/blob/riak_ts-1.3.0/rel/reltool.config#L5

Riak EE:

https://github.com/basho/riak_ee/blob/riak_ts_ee-1.3.0/rel/reltool.config#L5

**Comment by lukebakken** [comment]
@ooshlablu

**Comment by Basho-JIRA** [comment]
[~lbakken] - In previous releases we set this to the TS version, e.g., 1.2.0.  Are you sure we need 2.1.1? I know for client capabilities this would be useful to be 2.1+ 

**_[posted via JIRA by Brett Hazen]**_

**Comment by lukebakken** [comment]
@javajolt we definitely _need_ the same version as Riak EE: `2.1.1`

**Comment by Basho-JIRA** [comment]
[8:18 AM] Luke Bakken: It is fixed in the 1.3.1 tag: https://github.com/basho/riak/blob/riak_ts-1.3.1/rel/reltool.config
[8:18 AM] Luke Bakken: Let me make sure it's fixed in the right branch too
[8:19 AM] Luke Bakken: Yep, looks to be fixed https://github.com/basho/riak/commit/3f1a80bab659e844a12ddb21f25d9084e0af0940#diff-ee46c4f44a5bbed6a... 

**_[posted via JIRA by Derek Somogyi]**_

**Comment by Basho-JIRA** [comment]
[~lbakken] Sheeeeit.  OK. Then I just broke it with recent merges because I thought previously we had been using the TS numbering system, but Github tells me I'm delusional.  I'll fix.

**_[posted via JIRA by Brett Hazen]**_
