### ISSUE TITLE
Hel[!!! Challenge Setting up cluster using multiple nodes in single VM [JIRA: RIAK-2704]

### ISSUE THREAD

**Issue by RuyiOne** [basho/riak#863]
are there naming conventions to be adhered to when setting up cluster using multiple nodes in single VM. Been unable to start more than one machine because of the recurring error message.

Thanks

**Comment by seanjensengrey** [comment]
Hey RuyiOne,

It sounds like you are trying to setup a multi-node cluster on your local machine. This is totally doable.

I have a local 3 node cluster. The main thing to worry about is not having any collisions in the ports, below is a diff between `riak-a` and `riak-b` two nodes in my cluster.

Unpack the archive for an install, rename it and modify `etc/riak.conf` for each one so that ports are unique.

Start each node with the same cookie and then join them together.

It is late here. Will check back in the morning.

```
(x.env) ip-192-168-0-7:test-riak-3-node basho$ diff riak-a/etc/riak.conf riak-b/etc/riak.conf
1,3c1,7
< listener.protobuf.internal = 127.0.0.1:8087
< listener.http.internal = 127.0.0.1:8098
< handoff.port = 8099
---
> listener.protobuf.internal = 127.0.0.1:8187
> listener.http.internal = 127.0.0.1:8198
> handoff.port = 8199 
> 
> search.solr.port = 8193
> search.solr.jmx_port = 9985
> 
5,6d8
< search.solr.port = 8093
< search.solr.jmx_port = 8985
113c115
< nodename = riaka@127.0.0.1
---
> nodename = riakb@127.0.0.1
```

**Comment by RuyiOne** [comment]
Thanks. It was the naming convention.

nodename = riaka@127.0.0.1
nodename = riakb@127.0.0.1

I think documentation was a little fuzzy. Thanks again @seanjensengrey !!!
